### ISSUE TITLE
-bulk exits early?

### ISSUE THREAD

**Issue by adamdecaf** [globalsign/certlint#2]
Hi!

I was trying out `certlint` and I think the `-bulk` flag isn't setup quite right. I can't find in the code where the overall app is waiting for the concurrently spawned work is being executed. I have an [example file with 5 certs](https://github.com/adamdecaf/cert-manage/blob/master/testdata/lots.crt) that I get different results with `-cert` and `-bulk`.

`-cert`:

```
$ time ./certlint -cert ../../adamdecaf/cert-manage/testdata/lots.crt
Certificate Type: PS
Failed to verify chain for [Entrust.net Certification Authority (2048)]
./certlint -cert ../../adamdecaf/cert-manage/testdata/lots.crt  2.11s user 0.08s system 96% cpu 2.274 total
```

`-bulk`:

```
$ time ./certlint -bulk ../../adamdecaf/cert-manage/testdata/lots.crt
Checked 5 certificates
./certlint -bulk ../../adamdecaf/cert-manage/testdata/lots.crt  0.00s user 0.01s system 84% cpu 0.010 total
$ cat report.csv
Issuer,CN,O,Serial,NotBefore,NotAfter,Type,Error,Revoked,Cert
$ 
```

Code: https://github.com/globalsign/certlint/blob/master/certlint.go#L86

**Comment by vanbroup** [comment]
The difference between your first single run and the bulk run is that the single run is not using the chain builder. 

When checking a single certificate you need to give the issuer certificate too. But in a bulk check you could have many different issuers so they are automatically downloaded and added to a LRU cache.

The bulk check works with channels, reading and processing is using the jobs channel in doBulk and runBulk while saving is done by results channel in do and saveResults.

**Comment by adamdecaf** [comment]
@vanbroup I don't see where the code is waiting for results though. The `-bulk` command quits way too early to download anything. Here's a quick set of debugging lines along with a test run. Can you show an example of `-bulk` that generates a `report.csv` with lines? (All I get is a .csv file with headers)

```
diff --git a/certlint.go b/certlint.go
index 5d1434b..9f7e2b7 100644
--- a/certlint.go
+++ b/certlint.go
@@ -87,8 +87,10 @@ func main() {
        // save the results to a csv file.
        if len(*bulk) > 0 {
                for i := 1; i <= runtime.NumCPU(); i++ {
+                       fmt.Println("runBulk")
                        go runBulk(*expired)
                }
+               fmt.Println("saveResults")
                go saveResults(*report, *include, *revoked)
                doBulk(*bulk)
                return
@@ -258,6 +260,8 @@ func doBulk(bulk string) {
                                        e.Err(err.Error())
                                }

+                               fmt.Println("result")
+
                                results <- testResult{
                                        Cert:   nil,
                                        Pem:    string(pemCert),
```

```
adam@Planet-X -- certlint: (master ✗) ./certlint -bulk ../../adamdecaf/cert-manage/testdata/lots.crt
runBulk
runBulk
runBulk
runBulk
runBulk
runBulk
runBulk
runBulk
saveResults
Checked 5 certificates
```

**Comment by vanbroup** [comment]
Your comments are just along the initialization of the program (go ... means run in parallel), the results are collected here:
https://github.com/globalsign/certlint/blob/master/certlint.go#L301

**Comment by adamdecaf** [comment]
I was following along that. The problem I see is shouldn't there be a record of `result` being printed out before `testResult` is sent to `results` channel? My simple println trace isn't finding that.

Is there an example that does generate a proper `report.csv`? This code seems to not wait for any results to finish, which would kill the goroutines before they're done.

**Comment by vanbroup** [comment]
The bulk check only prints errors so if your certificates are fine nothing is printed. Maybe you can add one of the certificates in the testdata folder to your pem file?

The bulk method has been tested on pem files of tens of gigabytes but the intention this package doesn't hold any specific checks on that part of the library as it's more an example usage.
