### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by knweiss** [globalsign/certlint#3]
I like the idea of a Go X.509 certificate linter very much. Thanks for working on this!

However, the name clash with awslab's older and established [certlint](https://github.com/awslabs/certlint) is IMHO a little bit unfortunate.

Did you consider choosing a different project name?

**Comment by vanbroup** [comment]
Not really as it's a project in a different language.

**Comment by knweiss** [comment]
BTW: In the CLI usage example of the `README.md` you wrote "certlint**er**".

**Comment by christophprokop** [comment]
Hi there,

thanks for your effort! That is a useful tool!
But please do reconsider renaming it. You could really help to avoid name confusion in the future by putting this aside right now.
If linux distros will package certlint (both globalsign and awslabs) in the future there will need to be two different names anyway. You can now still choose the name before others will do it.
e.g. certlint-aws and certlint-gs or something like that might happen :/
certlinter doesn't sound that bad and as it's already documented that way? ;)

That it's written in another language isn't really the point here and most users won't even know about that.

Again: thanks for your efforts and for releasing it under a free license!
